### ISSUE TITLE
R2-6 uses post-R2-6 constructor of NDPluginStdArrays

### ISSUE THREAD

**Issue by btbouwens** [areaDetector/ADSimDetector#11]
commit f07ae52f52816c4733e7e5f491e4d9984c579a3b added a new additional parameter, so it's no longer compatible with ADCore R2-6.

**Comment by MarkRivers** [comment]
The release numbers in ADCore and ADSimDetector are not related.  The whole idea of splitting areaDetector into ADCore and separate driver repositories was that they could be released independently.

Here are the release dates:

ADCore R2-6  Feb. 19, 2017
ADCore R3-0  May 5, 2019
ADCore R3-1 July 3, 2017

ADSimDetector R2-6  July 4, 2017

This means that ADSimDetector R2-6 was built with ADCore R3-1.

It would be good if this were documented in the ADSimDetector RELEASE.md file.  Because the detector RELEASE files import the areaDetector/configure/RELEASE* files it is not obvious what version of ADCore a particular driver release was built with.
