### ISSUE TITLE
apply adl2ui conversion

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADSimDetector#4]
instead of #2

**Comment by prjemian** [comment]
images of converted screens

![simdetector](https://user-images.githubusercontent.com/2279984/33051917-f7947632-ce31-11e7-9bfc-9262d298261e.png)

![simdetectorsetup](https://user-images.githubusercontent.com/2279984/33051922-fa9a3074-ce31-11e7-9789-29dd363d2789.png)

**Comment by prjemian** [comment]
@MarkRivers : Added `op/Makefile` and `op/ui/Makefile` with local rules.  These should be adapted to the EPICS build system.  Perhaps @anjohnson can advise how to convert?  Is the advice in `/usr/local/epics/base/configure/CONFIG_FILE_TYPE` the right place to start?

Let's make it right for ADSimDetector before doing the same with [the similar work ADCore](https://github.com/areaDetector/ADCore/issues/297).

**Comment by MarkRivers** [comment]
It would be simpler to just to all the work in op/Makefile, and remove ui/Makefile and ui/autoconvert/Makefile. Then there is just one new file, and not 6 if we support op/edl and op/opi as well.

**Comment by anjohnson** [comment]
@prjemian I can show you how to export a set of build configuration settings and GNUmake rules from a support module so that other modules pointing to it can use those rules. That might be appropriate if you provided the file converters as support modules, but I suspect that isn't how you want to use them. I'd be happy to meet sometime after the holiday if you want to discuss the build system.

**Comment by prjemian** [comment]
@anjohnson : Thanks for the offer.  See you next week.

@MarkRivers : Shall I pull the rules from the `op/edl/Makefile` into `op/Makefile` as well?

**Comment by MarkRivers** [comment]
I tried doing what I proposed, having just op/Makefile.  But I am not sure down to make it work, because adl2ui does not let one set the output file.  It always creates file.ui in the current default directory.  Is there a way to cd to the ui/autoconvert directory before it runs adl2ui in op/Makefile?  If not then I guess we need the multiple Makefiles like you have it?

**Comment by prjemian** [comment]
I tried that too but had problems with formatting the target of the rule

**Comment by prjemian** [comment]
got it

**Comment by prjemian** [comment]
once this is acceptable, do a squash merge

**Comment by MarkRivers** [comment]
Can one do a squash merge on Github or only with the command line?

**Comment by anjohnson** [comment]
@MarkRivers If you click the downward arrow in the button to the right of the "Merge pull request" wording it gives you options to do that.
